routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */


Route::get('/test', function() {
    $beautymail = app()->make(Snowfire\Beautymail\Beautymail::class);
    $beautymail->send('emails.welcome', [], function($message) {
        $message
                ->from('bar@example.com')
                ->to('foo@gmail.com', 'John Smith')
                ->subject('Welcome!');
    });
});




Route::group(['as' => 'home.'], function() {
    Route::get('/', ['as' => 'index', 'uses' => 'HomeController@index']);
    Route::get('/about', ['as' => 'about', 'uses' => 'HomeController@getAbout']);
    Route::get('/conference', ['as' => 'conference', 'uses' => 'HomeController@getConference']);
    Route::get('/angel-network', ['as' => 'angel-network', 'uses' => 'HomeController@getAngelNetwork']);
    Route::get('/vc-tours', ['as' => 'vc-tours', 'uses' => 'HomeController@getVcTours']);

    Route::group(['as' => 'community.', 'prefix' => 'community'], function() {
        Route::post('/create', ['as' => 'create', 'uses' => 'CommunityController@create']);
        Route::post('/photo', ['as' => 'photo', 'uses' => 'CommunityController@uploadPhoto']);
        Route::get('/{tab?}', ['as' => 'index', 'uses' => 'HomeController@getCommunity']);
    });

    Route::group(['as' => 'event.', 'prefix' => 'event'], function() {
        Route::post('create', ['as' => 'create', 'uses' => 'EventController@create']);
        Route::post('photo', ['as' => 'photo', 'uses' => 'EventController@uploadPhoto']);
        Route::post('respond', ['as' => 'respond', 'uses' => 'EventController@respond']);
        Route::get('{tab?}', ['as' => 'index', 'uses' => 'EventController@showEvents']);
    });
});

// Authorization
Route::get('/login', ['as' => 'auth.login.form', 'uses' => 'Auth\SessionController@getLogin']);
Route::post('/login', ['as' => 'auth.login.attempt', 'uses' => 'Auth\SessionController@postLogin']);
Route::get('/logout', ['as' => 'auth.logout', 'uses' => 'Auth\SessionController@getLogout']);

// Registration
Route::get('register', ['as' => 'auth.register.form', 'uses' => 'Auth\RegistrationController@getRegister']);
Route::post('register', ['as' => 'auth.register.attempt', 'uses' => 'Auth\RegistrationController@postRegister']);

// Activation
Route::get('activate/{code}', ['as' => 'auth.activation.attempt', 'uses' => 'Auth\RegistrationController@getActivate']);
Route::get('resend', ['as' => 'auth.activation.request', 'uses' => 'Auth\RegistrationController@getResend']);
Route::post('resend', ['as' => 'auth.activation.resend', 'uses' => 'Auth\RegistrationController@postResend']);

// Password Reset
Route::get('password/reset/{code}', ['as' => 'auth.password.reset.form', 'uses' => 'Auth\PasswordController@getReset']);
Route::post('password/reset/{code}', ['as' => 'auth.password.reset.attempt', 'uses' => 'Auth\PasswordController@postReset']);
Route::get('password/reset', ['as' => 'auth.password.request.form', 'uses' => 'Auth\PasswordController@getRequest']);
Route::post('password/reset', ['as' => 'auth.password.request.attempt', 'uses' => 'Auth\PasswordController@postRequest']);

// Users
Route::resource('users', 'UserController');

// Roles
Route::resource('roles', 'RoleController');

// Dashboard
Route::get('dashboard', ['as' => 'dashboard', 'uses' => function() {
        return view('centaur.dashboard');
    }]);

//Admin Routes
Route::get('add-event', ['as' => 'admin.add.event', 'uses' => 'EventController@addEvent']);



//View users, events and communities profiles
Route::get('{slug}', 'ProfileController@view')->name('profile');

resources/views/layouts/app.blade.php
@extends('layouts.base')
@section('hero')
<div id="index-banner-app" class="parallax-container">
    <div class="section no-pad-bot">
        <!--  <div class="container">
            <br><br>
            <h1 class="header center deep-yellow-text text-lighten-1" style="opacity:0.95;">Awesome's Borderless...</h1>
            <div class="row center">
              <h5 class="header col s12 light">Join Over 5000 of tech's best people from across Nigeria and beyond at <b>#StartupSouth</b></h5>
            </div>
            <div class="row center">
              <a href="#" id="download-button" class="btn-large waves-effect waves-light deep-yellow black-text">Attend A #StartupSouth Event</a>
            </div>

          </div> -->
    </div>
    <div class="parallax"><img src="{{asset('img/startupsouth.jpg')}}" alt="Unsplashed background img 1"></div>
</div>


<div class="container">
    <div class="section">
        @yield('content')
        <!--   Icon Section   -->
    </div>
</div>
@endsection

@section('scripts')
<script type="text/javascript">
    $(document).ready(function () {
// the "href" attribute of the modal trigger must specify the modal ID that wants to be triggered
        $('.modal').modal();
        $('select').material_select();
    });
</script>
<script>
    // Hide Header on on scroll down
    var didScroll;
    var lastScrollTop = 0;
    var delta = 150;
    var navbarHeight = $('nav').outerHeight();

    $(window).scroll(function (event) {
        didScroll = true;
    });

    setInterval(function () {
        if (didScroll) {
            hasScrolled();
            didScroll = false;
        }
    }, 150);

    function hasScrolled() {
        var st = $(this).scrollTop();

        // Make sure they scroll more than delta
        if (Math.abs(lastScrollTop - st) <= delta)
            return;

        // If they scrolled down and are past the navbar, add class .nav-up.
        // This is necessary so you never see what is "behind" the navbar.
        if (st > lastScrollTop && st > navbarHeight) {
            // Scroll Down
            $('nav').removeClass('transparent').addClass('deep-green');
        } else {
            // Scroll Up
            if (st + $(window).height() < $(document).height()) {
                $('nav').removeClass('deep-green').addClass('transparent');
            }
        }

        lastScrollTop = st;
    }

</script>
@endsection

resources/views/layouts/base.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="apple-touch-icon" sizes="57x57" href="{{asset('img/favicon.ico')}}">
        <link rel="apple-touch-icon" sizes="60x60" href="{{asset('img/favicon.ico')}}">
        <link rel="icon" type="image/png" href="{{asset('img/favicon.ico')}}" sizes="32x32">
        <link rel="icon" type="image/png" href="{{asset('img/favicon.ico')}}" sizes="16x16">

        <link rel="shortcut icon" href="img/favicon.ico">

        <!-- CSS  -->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link href="{{asset('css/materialize.css')}}" type="text/css" rel="stylesheet" media="screen,projection"/>
        <link href="{{asset('css/animate.css')}}" type="text/css" rel="stylesheet" media="screen,projection"/>
        <link href="{{asset('css/style.css')}}" type="text/css" rel="stylesheet" media="screen,projection"/>
        <link href="https://fonts.googleapis.com/css?family=Bitter:700" rel="stylesheet">
        <script>
            window.Laravel = <?= json_encode(['csrfToken' => csrf_token()]); ?>;
            window.HomeUrl = '<?= rtrim(url('/'), '/') . '/'; ?>';
            window.env = '<?= app()->environment(); ?>';
        </script>

        <?php
        $defaultTitle = config('app.name');
        $defaultDescription = '';
        $defaultImage = asset('img/startupsouth.jpg');
        ?>
        <title>@yield('title',$defaultTitle)</title>
        <meta name="description" content="@yield('description',$defaultDescription)">
        <!--Twitter card-->
        <meta name="twitter:card" content="summary"/>
        <meta name="twitter:domain" content="{{url('/')}}"/>
        <meta name="twitter:description" content="@yield('description',$defaultDescription)"/>
        <meta name="twitter:title" content="@yield('title',$defaultTitle)"/>
        <meta name="twitter:image" content="@yield('image',$defaultImage)"/>
        <!--Open graph-->
        <meta property="og:url" content="{{url()->current()}}"/>
        <meta property="og:type" content="website"/>
        <meta property="og:description" content="@yield('description',$defaultDescription)"/>
        <meta property="og:title" content="@yield('title',$defaultTitle)"/>
        <meta property="og:image" content="@yield('image',$defaultImage)"/>
    </head>
    <body>

        <div class="navbar-fixed">
            <ul id="dropdown1" class="dropdown-content">
                <li><a href="{{ url('about') }}">History</a></li>
                <li><a href="#!">Why Regional</a></li>
                <li><a href="#!">Speakers and Mentors</a></li>
                <li><a href="#!">Partners</a></li>
                <li><a href="#!">Team</a></li>
                <li><a href="#!">Contact</a></li>
            </ul>
            <ul id="dropdown2" class="dropdown-content">
                <li><a href="#!">#StartupSouth1</a></li>
                <li><a href="#!">#StartupSouth2</a></li>
                <li><a href="#!">#StartupSouth3</a></li>
            </ul>
            <ul id="dropdown3" class="dropdown-content">
                <li><a href="{{route('home.community.index')}}">Communities</a></li>
                <li><a href="#!">Events</a></li>
                <li><a href="#!">Forum</a></li>
            </ul>

            <ul id="dropdown4" class="dropdown-content">
                <li><a href="#!">History</a></li>
                <li><a href="#!">Why Regional</a></li>
                <li><a href="#!">Speakers and Mentors</a></li>
                <li><a href="#!">Partners</a></li>
                <li><a href="#!">Team</a></li>
                <li><a href="#!">Contact</a></li>
            </ul>
            <ul id="dropdown5" class="dropdown-content">
                <li><a href="#!">#StartupSouth1</a></li>
                <li><a href="#!">#StartupSouth2</a></li>
                <li><a href="#!">#StartupSouth3</a></li>
            </ul>
            <ul id="dropdown6" class="dropdown-content">
                <li><a href="{{route('home.community.index')}}">Communities</a></li>
                <li><a href="#!">Events</a></li>
                <li><a href="#!">Forum</a></li>
            </ul>
            <nav class="transparent" role="navigation">
                <div class="nav-wrapper nav-container-fluid">
                    <ul id="nav-mobile" class="side-nav">
                        <li><a id="homepage" href="{{url('/')}}">Home</a></li>
                        <li><a class="dropdown-button" href="#!" data-activates="dropdown4">About<i class="material-icons right">arrow_drop_down</i></a></li>
                        <li><a href="#">Projects</a></li>
                        <li><a class="dropdown-button" href="#!" data-activates="dropdown5">Conference<i class="material-icons right">arrow_drop_down</i></a></li>
                        <li><a class="dropdown-button" href="#!" data-activates="dropdown6">Community<i class="material-icons right">arrow_drop_down</i></a></li>
                        <li><a href="#">Blog</a></li>
                        <li class="deep-yellow"><a class="black-text" href="#">Attend/Pitch</a></li>
                    </ul>
                    <a id="logo-container" href="#" class="brand-logo">
                        <img class="hide-on-med-and-down" src="{{asset('img/startupsouth_logo.png')}}" />
                        <img class="hide-on-large-only" src="{{asset('img/startupsouth_logo.png')}}" width="220px" height="auto" />
                    </a>
                    <ul class="right hide-on-med-and-down">
                        <li><a href="{{url('/')}}">Home</a></li>
                        <li><a class="dropdown-button" href="#!" data-activates="dropdown1">About<i class="material-icons right">arrow_drop_down</i></a></li>
                        <li><a href="#">Projects</a></li>
                        <li><a class="dropdown-button" href="#!" data-activates="dropdown2">Conference<i class="material-icons right">arrow_drop_down</i></a></li>
                        <li><a class="dropdown-button" href="#!" data-activates="dropdown3">Community<i class="material-icons right">arrow_drop_down</i></a></li>
                        <li><a href="#">Blog</a></li>
                        <li><a href="{{ url('/new-login') }}">Sign In/Sign Up</a></li>
                        <li class="deep-yellow"><a class="black-text" href="#">Attend/Pitch</a></li>
                    </ul>
                    <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons menu deep-yellow-text">menu</i></a>
                </div>
            </nav>
        </div>

        @yield('hero')

        <div id="index-region" class="parallax-container valign-wrapper">
            <div class="section no-pad-bot">
                <div class="container">
                    <div class="row center">
                        <h5 class="header region home-lead col s12 deep-green-text">11 States, 13 Cities, 650+KM<sup>2</sup> and over 50Million People.</h5>
                    </div>
                </div>
            </div>
            <div class="parallax"><!--<img src="img/background2.jpg" alt="Unsplashed background img 2"> --> <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d1015710.1827876485!2d7.2059022421874985!3d6.047045513919724!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sng!4v1502310942290" width="100%" height="450" frameborder="0" style="border:0" allowfullscreen></iframe></div>
        </div>

        @yield('post_content')

        <div id="index-contact" class="parallax-container valign-wrapper">
            <div class="section no-pad-bot">
                <div class="container">
                    <div class="row">
                        <h5 class="header col s12 light center-align">Stay connected, subscribe to our newsletter.</h5>
                        <form action="#" onclick="return false;" id="home-newsletter" class="col s12 m8 offset-m2">
                            <row class="">
                                <div class="input-field home-newsletter">
                                    <input class="col m8 s12 browser-default newsletter" placeholder="yourname@example.com" id="name" type="email" require>
                                </div>
                                <div class="input-field">
                                    <input type="submit" role="button" class="btn main-search deep-yellow black-text col l4 m4 s12"  value="Submit">
                                </div>
                            </row>
                        </form>
                    </div>
                </div>
            </div>
            <div class="parallax"><img src="{{asset('img/startupsouth-base.jpg')}}" alt="Unsplashed background img 3"></div>
        </div>

        <footer class="page-footer deep-green">
            <div class="container footer-container-fluid">
                <div class="row">
                    <div class="col l5 s12">
                        <h6 class="white-text home-lead">About #StartupSouth</h6>
                        <p class="grey-text text-lighten-4">The simple goal of #StartupSouth is to Connect, Expose and Attract Investment to Startups and Founders residing and operating out of South-South and South-East Nigeria.</p>


                    </div>
                    <div class="col l4 s12">
                        <h6 class="white-text home-lead">Explore</h6>
                        <ul>
                            <li><a class="white-text" href="{{route('home.community.index',['tab'=>'startups'])}}">#StartupSouth Startups</a></li>
                            <!--                            <li><a class="white-text" href="#!">Tech Events in The Niger Delta</a></li>
                                                        <li><a class="white-text" href="#!">Tech Events in South-East</a></li>-->
                            <li><a class="white-text" href="{{route('home.community.index')}}">Explore Our Community</a></li>
                            <li><a class="white-text" href="{{route('home.community.index',['tab'=>'hubs'])}}">Hubs/Co-Working Spaces</a></li>
                            <li><a class="white-text" href="#!">Contact #StartupSouth</a></li>
                        </ul>
                    </div>
                    <div class="col l3 s12">
                        <h6 class="white-text home-lead">Connect</h6>
                        <ul class="inline">
                            <li><a class="white-text" href="#!"><img src="{{asset('img/facebook-logo.png')}}" width="45px" height="45px"/></a></li>
                            <li><a class="white-text" href="#!"><img src="{{asset('img/instagram-logo.png')}}" width="45px" height="45px"/></a></li>
                            <li><a class="white-text" href="#!"><img src="{{asset('img/twitter-logo.png')}}" width="45px" height="45px"></a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="footer-copyright">
                <div class="container footer-container-fluid">
                    Made with <svg style="width:24px;height:24px; margin-top:100px;" viewBox="0 0 24 24">
                    <path fill="#ffc400" d="M12,21.35L10.55,20.03C5.4,15.36 2,12.27 2,8.5C2,5.41 4.42,3 7.5,3C9.24,3 10.91,3.81 12,5.08C13.09,3.81 14.76,3 16.5,3C19.58,3 22,5.41 22,8.5C22,12.27 18.6,15.36 13.45,20.03L12,21.35Z" />
                    </svg> by <a class="green-text text-lighten-1 text-lighten-3" href="#">Havilah & Hills</a>
                </div>
            </div>
        </footer>


        <!--  Scripts-->
        <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
        <script src="{{asset('js/materialize.js')}}"></script>
        <script src="{{asset('js/init.js')}}"></script>
        @yield('scripts')
    </body>
</html>

resources/views/layouts/dash-header.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>@yield('title')</title>

    <!-- Bootstrap -->
    <link href="vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="vendors/nprogress/nprogress.css" rel="stylesheet">
    <!-- iCheck -->
    <link href="vendors/iCheck/skins/flat/green.css" rel="stylesheet">
	
    <!-- bootstrap-progressbar -->
    <link href="vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet">
    <!-- JQVMap -->
    <link href="vendors/jqvmap/dist/jqvmap.min.css" rel="stylesheet"/>
    <!-- bootstrap-daterangepicker -->
    <link href="vendors/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="build/css/custom.min.css" rel="stylesheet">
  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <div class="col-md-3 left_col">
          <div class="left_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
              <a href="index.html" class="site_title"><i class="fa fa-paw"></i> <span>#StartUpSouth Dashboard!</span></a>
            </div>

            <div class="clearfix"></div>

            <!-- menu profile quick info -->
            <div class="profile clearfix">
              <div class="profile_pic">
                <img src="images/img.jpg" alt="..." class="img-circle profile_img">
              </div>
              <div class="profile_info">
                <span>Welcome,</span>
                @if (Sentinel::check())
                <h2>{{ Sentinel::getUser()->first_name }}</h2>
                @else
                <h2>Guest</h2>
                @endif
              </div>
            </div>
            <!-- /menu profile quick info -->

            <br />

            <!-- sidebar menu -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
                <h3>General</h3>
                <ul class="nav side-menu">
                    @if (Sentinel::check() && Sentinel::inRole('administrator'))
                  <li><a><i class="fa fa-home"></i> Communities <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="#">View All</a></li>
                      <li><a href="#">Add Community</a></li>
                      <li><a href="#">Approvals</a></li>
                    </ul>
                  </li>
                  <li><a><i class="fa fa-edit"></i>Events <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="#">View Events</a></a></li>
                      <li><a href="{{route('admin.add.event')}}">Add Event</a></li>
                      
                    </ul>
                  </li>
                  <li><a><i class="fa fa-desktop"></i> Angel Network <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="#">Applications</a></li>
                      <li><a href="#">Add Angel</a></li>
                      <li><a href="#">View All Angels</a></li>
                      
                    </ul>
                  </li>
                  <li><a><i class="fa fa-sitemap"></i>VC Tours <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="#"></a>View Applications </a></li>
                      <li><a href="#">Add VC</a></li>
                      <li><a href="#">View All VCs</a></li>
                      
                    </ul>
                  </li>
                  
                            <li class="{{ Request::is('users*') ? 'active' : '' }}"><a href="{{ route('users.index') }}"><i class="fa fa-user"></i>Users</a></li>
                            <li class="{{ Request::is('roles*') ? 'active' : '' }}"><a href="{{ route('roles.index') }}"><i class="fa fa-bar-chart-o"></i> Roles</a></li>
                            
                        @endif
                  
                  
                </ul>
              </div>
              <div class="menu_section">
                <h3>Live On</h3>
                <ul class="nav side-menu">
                  <li><a><i class="fa fa-bug"></i> Additional Pages <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="e_commerce.html">E-commerce</a></li>
                      <li><a href="projects.html">Projects</a></li>
                      <li><a href="project_detail.html">Project Detail</a></li>
                      <li><a href="contacts.html">Contacts</a></li>
                      <li><a href="profile.html">Profile</a></li>
                    </ul>
                  </li>
                  <li><a><i class="fa fa-windows"></i> Extras <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="page_403.html">403 Error</a></li>
                      <li><a href="page_404.html">404 Error</a></li>
                      <li><a href="page_500.html">500 Error</a></li>
                      <li><a href="plain_page.html">Plain Page</a></li>
                      <li><a href="login.html">Login Page</a></li>
                      <li><a href="pricing_tables.html">Pricing Tables</a></li>
                    </ul>
                  </li>
                  <li><a><i class="fa fa-sitemap"></i> Multilevel Menu <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                        <li><a href="#level1_1">Level One</a>
                        <li><a>Level One<span class="fa fa-chevron-down"></span></a>
                          <ul class="nav child_menu">
                            <li class="sub_menu"><a href="level2.html">Level Two</a>
                            </li>
                            <li><a href="#level2_1">Level Two</a>
                            </li>
                            <li><a href="#level2_2">Level Two</a>
                            </li>
                          </ul>
                        </li>
                        <li><a href="#level1_2">Level One</a>
                        </li>
                    </ul>
                  </li>                  
                  <li><a href="javascript:void(0)"><i class="fa fa-laptop"></i> Landing Page <span class="label label-success pull-right">Coming Soon</span></a></li>
                </ul>
              </div>

            </div>
            <!-- /sidebar menu -->

            <!-- /menu footer buttons -->
            <div class="sidebar-footer hidden-small">
              <a data-toggle="tooltip" data-placement="top" title="Settings">
                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="Lock">
                <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="Logout" href="login.html">
                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
              </a>
            </div>
            <!-- /menu footer buttons -->
          </div>
        </div>

        <!-- top navigation -->
        <div class="top_nav">
          <div class="nav_menu">
            <nav>
              <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
              </div>

              <ul class="nav navbar-nav navbar-right">
                  @if (Sentinel::check())
                            <li> <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <img src="images/img.jpg" alt="">{{ Sentinel::getUser()->email }}<span class=" fa fa-angle-down"></span>
                  </a>
                  <ul class="dropdown-menu dropdown-usermenu pull-right">
                    <li><a href="javascript:;"> Profile</a></li>
                    <li>
                      <a href="javascript:;">
                        <span class="badge bg-red pull-right">50%</span>
                        <span>Settings</span>
                      </a>
                    </li>
                    <li><a href="javascript:;">Help</a></li>
                    <li><a href="{{ route('auth.logout') }}"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
                  </ul></li>
                            
                        @else
                            <li><a href="{{ route('auth.login.form') }}">Login</a></li>
                            <li><a href="{{ route('auth.register.form') }}">Register</a></li>
                        @endif
                        
                        <li class="{{ Request::is('/dashboard') ? 'active' : '' }}"><a href="{{ route('dashboard') }}">Dashboard</a></li>
                        
                
               
                
              </ul>
            </nav>
          </div>
        </div>
        
        @include('Centaur::notifications')
        @yield('content')
        
        
        <footer>
          <div class="pull-right">
            #StartUpSouth -  &copy;2017
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
      </div>
    </div>

    <!-- jQuery -->
    <script src="vendors/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="vendors/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- FastClick -->
    <script src="vendors/fastclick/lib/fastclick.js"></script>
    <!-- NProgress -->
    <script src="vendors/nprogress/nprogress.js"></script>
    <!-- Chart.js -->
    <script src="vendors/Chart.js/dist/Chart.min.js"></script>
    <!-- gauge.js -->
    <script src="vendors/gauge.js/dist/gauge.min.js"></script>
    <!-- bootstrap-progressbar -->
    <script src="vendors/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
    <!-- iCheck -->
    <script src="vendors/iCheck/icheck.min.js"></script>
    <!-- Skycons -->
    <script src="vendors/skycons/skycons.js"></script>
    <!-- Flot -->
    <script src="vendors/Flot/jquery.flot.js"></script>
    <script src="vendors/Flot/jquery.flot.pie.js"></script>
    <script src="vendors/Flot/jquery.flot.time.js"></script>
    <script src="vendors/Flot/jquery.flot.stack.js"></script>
    <script src="vendors/Flot/jquery.flot.resize.js"></script>
    <!-- Flot plugins -->
    <script src="vendors/flot.orderbars/js/jquery.flot.orderBars.js"></script>
    <script src="vendors/flot-spline/js/jquery.flot.spline.min.js"></script>
    <script src="vendors/flot.curvedlines/curvedLines.js"></script>
    <!-- DateJS -->
    <script src="vendors/DateJS/build/date.js"></script>
    <!-- JQVMap -->
    <script src="vendors/jqvmap/dist/jquery.vmap.js"></script>
    <script src="vendors/jqvmap/dist/maps/jquery.vmap.world.js"></script>
    <script src="vendors/jqvmap/examples/js/jquery.vmap.sampledata.js"></script>
    <!-- bootstrap-daterangepicker -->
    <script src="vendors/moment/min/moment.min.js"></script>
    <script src="vendors/bootstrap-daterangepicker/daterangepicker.js"></script>

    <!-- Custom Theme Scripts -->
    <script src="build/js/custom.min.js"></script>
	
  </body>
</html>